from jinja2 import Template

template: Template = Template("""version: {{ config_standard }}

# Automatically generated by 'restic_backup_report config generate'.
# Do not modify any values in the 'secrets' section.
# Changing these values will make the configuration invalid and may
# prevent the master key from being verified.
#
# IMPORTANT: If you lose the master key, you will need to generate
# a new configuration.

secrets:
    checksum: {{ master_key_checksum }}
    salt: {{ master_key_checksum_salt }}
""")